apiVersion: v1
kind: Service
metadata:
        name: springjpa-service
        labels: 
            name: springjpa-service
            app: springjpa-app
spec:
        type: NodePort
        ports:
          - port: 8080
            targetPort: 8080
            nodePort: 30004
        selector:
          name: springjpa
          app: springjpa-app

