apiVersion: v1
kind: Service
metadata:
        name: mysqldb
        labels: 
            name: mysql-service
            app: springjpa-app
spec:
        ports:
          - port: 3306
            targetPort: 3306
        selector:
          name: mysqldb
          app: springjpa-app

