apiVersion: v1
kind: Pod
metadata: 
  name: mysqldb
  labels:
          name: mysqldb
          app: springjpa-app
spec:
        containers:
                - name: mysql-container
                  image: mysql
                  env:
                          - name: MYSQL_ROOT_PASSWORD
                            value: "root@123"
                          - name: MYSQL_DATABASE
                            value: "db_example"
                  ports:
                          - containerPort: 3306
